spring:
  application:
    name: ingest-service
  redis:
    #add "127.0.0.1 redis" without quote in /etc/hosts for running without docker when redis running locally. 
    host: redis
    port: 6379
  kafka:
    #add "127.0.0.1 kafka" without quote in /etc/hosts for running without docker when kafka running locally.  
    bootstrap-servers: kafka:9092
    producer:
      auto-offset-reset: earliest
      group-id: boot
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
