spring:
  application:
    name: store-service
  data:
    mongodb:
      #add "127.0.0.1 mongo" without quote in /etc/hosts for running without docker when mongo running locally.
      host: mongo
      port: 27017
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
server: 
  port: 8282